[client] Reset config at app shutdown
SeisComP/common pull request #49
Opened 2022-01-11 15:45 UTC by damb

In accordance to #11.

2022-01-12 08:27 UTC, gempa-jabe requested changes

2022-01-12 08:27 UTC, gempa-jabe commented on libs/seiscomp/client/application.cpp
> +		} else {
Please move `else` to a new line, see above for an example.

2022-01-12 08:27 UTC, gempa-jabe commented on libs/seiscomp/client/configdb.cpp
> +void ConfigDB::setConfig(DataModel::Config* config) {
Please attach the asterisk to `config`,  `DataModel::Config *config`.

2022-01-12 08:27 UTC, gempa-jabe commented on libs/seiscomp/client/configdb.h
> +		void setConfig(DataModel::Config* config);
Please attach the asterisk to config, see other comment.

2022-01-12 09:11 UTC, gempa-jabe commented
Great, thanks.

2022-01-12 09:11 UTC, merged

2022-01-14 14:35 UTC, damb commented
Note that with this PR, modules not explicitly requiring a loading the config module must call `setLoadConfigModuleEnabled(false)`. This is the default, anyway https://github.com/SeisComP/common/blob/df83362fbb6ea29eeef3f9b2a609e6984f017a2f/libs/seiscomp/client/application.cpp#L273

2022-01-14 14:41 UTC, gempa-jabe commented
Why must they call it if it is the default? I can't follow your statement right now (it is Friday ;) ). Does this PR brake current behaviour with respect  to initialization?

2022-01-14 15:08 UTC, damb commented
Well, I'm not 100% sure, however, a call to e.g. `bindings2cfg --key-dir ./etc/key -o config.xml` previously succeeded without explicitly specifying a config DB. Now, it fails due to https://github.com/SeisComP/common/blob/df83362fbb6ea29eeef3f9b2a609e6984f017a2f/libs/seiscomp/client/application.cpp#L1050-L1053

if not setting the DB.

2022-01-20 09:02 UTC, gempa-jabe commented
Well then we have to fix bindings2cfg.

2022-01-20 10:08 UTC, gempa-jabe commented
Fixed with c127b41f8e1fc323148b257ff92afe555ae515e5.

2022-01-20 16:14 UTC, damb commented
Thanks.

2022-01-26 10:33 UTC, gempa-jabe commented
I have to reopen the PR. The fix with `setConfig` causes an application to crash if it is created after another application has been destroyed and both need to read the configuration. Actually we need to reset the instance and not the config object. I will fix that but check with you if you require `ConfigDB::setConfig(...)` or if it was only necessary for this particular issue.

2022-01-26 10:57 UTC, gempa-jabe commented
I have added a `Reset` method to all singletons which are called in the respective applications. That fixes a crash and furthermore also cleans up the loaded plugins.

2022-02-01 10:24 UTC, damb commented
@gempa-jabe, thanks for rechecking. The implemented solution works for me, too.

Originally, I used `ConfigDB::setConfig(...)` in order to have it aligned with `Inventory::setInventory(...)`. I wasn't aware of the fact that the underlying config object is reused under certain circumstances.