[stdloc] fix config documentation and debug logs
SeisComP/common pull request #99
Opened 2023-08-08 16:46 UTC by luca-s

Just a couple of minor changes that do not affect the code behaviour.

2023-08-08 17:17 UTC, gempa-dirk requested changes

2023-08-09 10:19 UTC, luca-s commented on plugins/locator/stdloc/descriptions/global_stdloc.xml
> +									value affects the uncertainty of the location and the number of
Updating the documentation soon...

2023-08-09 10:55 UTC, luca-s commented
Just updated the PR

2023-08-09 11:13 UTC, gempa-dirk approved these changes
Thank you for considering the comments.

2023-08-16 08:27 UTC, merged